const MODULE_NAME = "[DASHBOARD]";

const ActionTypes = {
  FETCH_USER_SUCCESS: `${MODULE_NAME} FETCH_USER_SUCCESS`,
  FETCH_USER_FAILURE: `${MODULE_NAME} FETCH_USER_FAILURE`,
  DELETE_USER_SUCCESS: `${MODULE_NAME} DELETE_USER_SUCCESS`,
  DELETE_USER_FAILURE: `${MODULE_NAME} DELETE_USER_FAILURE`,
  ADD_USER_SUCCSESS: `${MODULE_NAME} ADD_USER_SUCCSESS`,
  ADD_USER_FAILURE: `${MODULE_NAME} ADD_USER_FAILURE`,
  FETCH_SINGLE_USER_SUCCESS: `${MODULE_NAME} FETCH_SINGLE_USER_SUCCESS`,
  FETCH_SINGLE_USER_FAILURE: `${MODULE_NAME} FETCH_SINGLE_USER_FAILURE`,
  EDIT_USER_SUCCESS: `${MODULE_NAME} EDIT_USER_SUCCESS`,
  EDIT_USER_FAILURE: `${MODULE_NAME} EDIT_USER_FAILURE`,
  SEARCH_USER_SUCCESS: `${MODULE_NAME} SEARCH_USER_SUCCESS`,
  SEARCH_USER_FAILURE: `${MODULE_NAME} SEARCH_USER_FAILURE`,
  SHOW_LOADING: `${MODULE_NAME} SHOW_LOADING`,
  HIDE_LOADING: `${MODULE_NAME} HIDE_LOADING`,
};

export default ActionTypes;
